[build] 
    command = "yarn build"
    build = "build"

[build.environment]
  # Disable npm/node processing
  NODE_VERSION = "18"
  # Prevent npm install
  NPM_FLAGS = "--production=false"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 