[build]
  # No build command needed for static HTML
  command = "ls -la && echo 'Static site - no build needed'"
  # Publish the root directory where index.html is located
  publish = "."
  # Skip build if no changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  # Disable npm/node processing
  NODE_VERSION = "18"
  # Prevent npm install
  NPM_FLAGS = "--production=false"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 