[build]
  # No build command needed for static HTML
  command = ""
  # Publish the root directory
  publish = "."

[build.environment]
  # Disable npm/node processing
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 